//===- QThreadImpl.cpp ----------------------------------------------------===//
//
//                              The SkyPat team
//
// This file is distributed under the New BSD License.
// See LICENSE for details.
//
//===----------------------------------------------------------------------===//
#include <skymizer/Thread/ThreadImpl.h>

using namespace skymizer;

//===----------------------------------------------------------------------===//
// QThreadImpl - Quick Thread
//===----------------------------------------------------------------------===//

