Document: pat
Title: Debian pat Manual
Author: <insert document author here>
Abstract: This manual describes what pat is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pat/pat.sgml.gz

Format: postscript
Files: /usr/share/doc/pat/pat.ps.gz

Format: text
Files: /usr/share/doc/pat/pat.text.gz

Format: HTML
Index: /usr/share/doc/pat/html/index.html
Files: /usr/share/doc/pat/html/*.html
